//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace HardwareSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraSettings
    {
    
        private string _cameraName;
    
        private int _frameRate;
    
        private int _exposure;
    
        private double _dutyCycle;
    
        private string _serialNumber;
    
        private string _ffmpegInput;
    
        private string _ffmpegOutput;
    
        public CameraSettings()
        {
        }
    
        protected CameraSettings(CameraSettings other)
        {
            _cameraName = other._cameraName;
            _frameRate = other._frameRate;
            _exposure = other._exposure;
            _dutyCycle = other._dutyCycle;
            _serialNumber = other._serialNumber;
            _ffmpegInput = other._ffmpegInput;
            _ffmpegOutput = other._ffmpegOutput;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera_name")]
        public string CameraName
        {
            get
            {
                return _cameraName;
            }
            set
            {
                _cameraName = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frame_rate")]
        public int FrameRate
        {
            get
            {
                return _frameRate;
            }
            set
            {
                _frameRate = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="exposure")]
        public int Exposure
        {
            get
            {
                return _exposure;
            }
            set
            {
                _exposure = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="duty_cycle")]
        public double DutyCycle
        {
            get
            {
                return _dutyCycle;
            }
            set
            {
                _dutyCycle = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serial_number")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ffmpeg_input")]
        public string FfmpegInput
        {
            get
            {
                return _ffmpegInput;
            }
            set
            {
                _ffmpegInput = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ffmpeg_output")]
        public string FfmpegOutput
        {
            get
            {
                return _ffmpegOutput;
            }
            set
            {
                _ffmpegOutput = value;
            }
        }
    
        public System.IObservable<CameraSettings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraSettings(this)));
        }
    
        public System.IObservable<CameraSettings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraSettings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CameraName = " + _cameraName + ", ");
            stringBuilder.Append("FrameRate = " + _frameRate + ", ");
            stringBuilder.Append("Exposure = " + _exposure + ", ");
            stringBuilder.Append("DutyCycle = " + _dutyCycle + ", ");
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("FfmpegInput = " + _ffmpegInput + ", ");
            stringBuilder.Append("FfmpegOutput = " + _ffmpegOutput);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraSettings1
    {
    
        private string _cameraName;
    
        private int _frameRate;
    
        private int _exposure;
    
        private double _dutyCycle;
    
        private string _serialNumber;
    
        private string _ffmpegInput;
    
        private string _ffmpegOutput;
    
        public CameraSettings1()
        {
        }
    
        protected CameraSettings1(CameraSettings1 other)
        {
            _cameraName = other._cameraName;
            _frameRate = other._frameRate;
            _exposure = other._exposure;
            _dutyCycle = other._dutyCycle;
            _serialNumber = other._serialNumber;
            _ffmpegInput = other._ffmpegInput;
            _ffmpegOutput = other._ffmpegOutput;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera_name")]
        public string CameraName
        {
            get
            {
                return _cameraName;
            }
            set
            {
                _cameraName = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frame_rate")]
        public int FrameRate
        {
            get
            {
                return _frameRate;
            }
            set
            {
                _frameRate = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="exposure")]
        public int Exposure
        {
            get
            {
                return _exposure;
            }
            set
            {
                _exposure = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="duty_cycle")]
        public double DutyCycle
        {
            get
            {
                return _dutyCycle;
            }
            set
            {
                _dutyCycle = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serial_number")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ffmpeg_input")]
        public string FfmpegInput
        {
            get
            {
                return _ffmpegInput;
            }
            set
            {
                _ffmpegInput = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ffmpeg_output")]
        public string FfmpegOutput
        {
            get
            {
                return _ffmpegOutput;
            }
            set
            {
                _ffmpegOutput = value;
            }
        }
    
        public System.IObservable<CameraSettings1> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraSettings1(this)));
        }
    
        public System.IObservable<CameraSettings1> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraSettings1(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("CameraName = " + _cameraName + ", ");
            stringBuilder.Append("FrameRate = " + _frameRate + ", ");
            stringBuilder.Append("Exposure = " + _exposure + ", ");
            stringBuilder.Append("DutyCycle = " + _dutyCycle + ", ");
            stringBuilder.Append("SerialNumber = " + _serialNumber + ", ");
            stringBuilder.Append("FfmpegInput = " + _ffmpegInput + ", ");
            stringBuilder.Append("FfmpegOutput = " + _ffmpegOutput);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DeLuxDriver
    {
    
        private string _comPort;
    
        private int _ch1Current;
    
        private int _ch1PulseFrequency;
    
        private double _ch1PulseDutyCycle;
    
        private int _ch2Current;
    
        private int _ch2PulseFrequency;
    
        private double _ch2PulseDutyCycle;
    
        private int _ch3Current;
    
        private int _ch3PulseFrequency;
    
        private double _ch3PulseDutyCycle;
    
        public DeLuxDriver()
        {
        }
    
        protected DeLuxDriver(DeLuxDriver other)
        {
            _comPort = other._comPort;
            _ch1Current = other._ch1Current;
            _ch1PulseFrequency = other._ch1PulseFrequency;
            _ch1PulseDutyCycle = other._ch1PulseDutyCycle;
            _ch2Current = other._ch2Current;
            _ch2PulseFrequency = other._ch2PulseFrequency;
            _ch2PulseDutyCycle = other._ch2PulseDutyCycle;
            _ch3Current = other._ch3Current;
            _ch3PulseFrequency = other._ch3PulseFrequency;
            _ch3PulseDutyCycle = other._ch3PulseDutyCycle;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="com_port")]
        public string ComPort
        {
            get
            {
                return _comPort;
            }
            set
            {
                _comPort = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch1_current")]
        public int Ch1Current
        {
            get
            {
                return _ch1Current;
            }
            set
            {
                _ch1Current = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch1_pulse_frequency")]
        public int Ch1PulseFrequency
        {
            get
            {
                return _ch1PulseFrequency;
            }
            set
            {
                _ch1PulseFrequency = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch1_pulse_duty_cycle")]
        public double Ch1PulseDutyCycle
        {
            get
            {
                return _ch1PulseDutyCycle;
            }
            set
            {
                _ch1PulseDutyCycle = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch2_current")]
        public int Ch2Current
        {
            get
            {
                return _ch2Current;
            }
            set
            {
                _ch2Current = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch2_pulse_frequency")]
        public int Ch2PulseFrequency
        {
            get
            {
                return _ch2PulseFrequency;
            }
            set
            {
                _ch2PulseFrequency = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch2_pulse_duty_cycle")]
        public double Ch2PulseDutyCycle
        {
            get
            {
                return _ch2PulseDutyCycle;
            }
            set
            {
                _ch2PulseDutyCycle = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch3_current")]
        public int Ch3Current
        {
            get
            {
                return _ch3Current;
            }
            set
            {
                _ch3Current = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch3_pulse_frequency")]
        public int Ch3PulseFrequency
        {
            get
            {
                return _ch3PulseFrequency;
            }
            set
            {
                _ch3PulseFrequency = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="ch3_pulse_duty_cycle")]
        public double Ch3PulseDutyCycle
        {
            get
            {
                return _ch3PulseDutyCycle;
            }
            set
            {
                _ch3PulseDutyCycle = value;
            }
        }
    
        public System.IObservable<DeLuxDriver> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DeLuxDriver(this)));
        }
    
        public System.IObservable<DeLuxDriver> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DeLuxDriver(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ComPort = " + _comPort + ", ");
            stringBuilder.Append("Ch1Current = " + _ch1Current + ", ");
            stringBuilder.Append("Ch1PulseFrequency = " + _ch1PulseFrequency + ", ");
            stringBuilder.Append("Ch1PulseDutyCycle = " + _ch1PulseDutyCycle + ", ");
            stringBuilder.Append("Ch2Current = " + _ch2Current + ", ");
            stringBuilder.Append("Ch2PulseFrequency = " + _ch2PulseFrequency + ", ");
            stringBuilder.Append("Ch2PulseDutyCycle = " + _ch2PulseDutyCycle + ", ");
            stringBuilder.Append("Ch3Current = " + _ch3Current + ", ");
            stringBuilder.Append("Ch3PulseFrequency = " + _ch3PulseFrequency + ", ");
            stringBuilder.Append("Ch3PulseDutyCycle = " + _ch3PulseDutyCycle);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DelphiController
    {
    
        private string _comPort;
    
        private int _pokePin;
    
        private int _maxOdorDeliveryTimeUs;
    
        private int _minPokeTimeUs;
    
        private int _minOdorDeliveryTimeUs;
    
        private int _odorSetupTimeUs;
    
        private int _pokePin;
    
        private int _vacuumSetupTimeUs;
    
        private int _vacuumCloseTimeUs;
    
        private int _odorDwellTimeUs;
    
        public DelphiController()
        {
        }
    
        protected DelphiController(DelphiController other)
        {
            _comPort = other._comPort;
            _pokePin = other._pokePin;
            _maxOdorDeliveryTimeUs = other._maxOdorDeliveryTimeUs;
            _minPokeTimeUs = other._minPokeTimeUs;
            _minOdorDeliveryTimeUs = other._minOdorDeliveryTimeUs;
            _odorSetupTimeUs = other._odorSetupTimeUs;
            _odorDwellTimeUs = other._odorDwellTimeUs;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="com_port")]
        public string ComPort
        {
            get
            {
                return _comPort;
            }
            set
            {
                _comPort = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="poke_pin")]
        public int PokePin
        {
            get
            {
                return _pokePin;
            }
            set
            {
                _pokePin = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="max_odor_delivery_time_us")]
        public int MaxOdorDeliveryTimeUs
        {
            get
            {
                return _maxOdorDeliveryTimeUs;
            }
            set
            {
                _maxOdorDeliveryTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_poke_time_us")]
        public int MinPokeTimeUs
        {
            get
            {
                return _minPokeTimeUs;
            }
            set
            {
                _minPokeTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_odor_delivery_time_us")]
        public int MinOdorDeliveryTimeUs
        {
            get
            {
                return _minOdorDeliveryTimeUs;
            }
            set
            {
                _minOdorDeliveryTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_setup_time_us")]
        public int OdorSetupTimeUs
        {
            get
            {
                return _odorSetupTimeUs;
            }
            set
            {
                _odorSetupTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_dwell_time_us")]
        public int OdorDwellTimeUs
        {
            get
            {
                return _odorDwellTimeUs;
            }
            set
            {
                _pokePin = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="vacuum_setup_time_us")]
        public int VacuumSetupTimeUs
        {
            get
            {
                return _vacuumSetupTimeUs;
            }
            set
            {
                _vacuumSetupTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="vacuum_close_time_us")]
        public int VacuumCloseTimeUs
        {
            get
            {
                return _vacuumCloseTimeUs;
            }
            set
            {
                _vacuumCloseTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_dwell_time_us")]
        public int OdorDwellTimeUs
        {
            get
            {
                return _odorDwellTimeUs;
            }
            set
            {
                _odorDwellTimeUs = value;
            }
        }
    
        public System.IObservable<DelphiController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DelphiController(this)));
        }
    
        public System.IObservable<DelphiController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DelphiController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ComPort = " + _comPort + ", ");
            stringBuilder.Append("PokePin = " + _pokePin + ", ");
            stringBuilder.Append("MaxOdorDeliveryTimeUs = " + _maxOdorDeliveryTimeUs + ", ");
            stringBuilder.Append("MinPokeTimeUs = " + _minPokeTimeUs + ", ");
            stringBuilder.Append("MinOdorDeliveryTimeUs = " + _minOdorDeliveryTimeUs + ", ");
            stringBuilder.Append("OdorSetupTimeUs = " + _odorSetupTimeUs + ", ");
            stringBuilder.Append("OdorDwellTimeUs = " + _odorDwellTimeUs);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class FluidicSettings
    {
    
        private int _leakFlowmeterAdc;
    
        private double _leakThreshold;
    
        private int _manualFlometerAdc;
    
        private double _manualFlowmeterTargetFlowRate;
    
        private double _manualFlowmeterFlowRateTolerance;
    
        private int _proportionalValveFlowmeter0Adc;
    
        private double _proportionalValveFlowmeter0TargetFlowrate;
    
        private int _proportionalValveFlowmeter1Adc;
    
        private double _proportionalValveFlowmeter1TargetFlowrate;
    
        private int _proportionalValveFlowmeter2Adc;
    
        private double _proportionalValveFlowmeter2TargetFlowrate;
    
        public FluidicSettings()
        {
        }
    
        protected FluidicSettings(FluidicSettings other)
        {
            _leakFlowmeterAdc = other._leakFlowmeterAdc;
            _leakThreshold = other._leakThreshold;
            _manualFlometerAdc = other._manualFlometerAdc;
            _manualFlowmeterTargetFlowRate = other._manualFlowmeterTargetFlowRate;
            _manualFlowmeterFlowRateTolerance = other._manualFlowmeterFlowRateTolerance;
            _proportionalValveFlowmeter0Adc = other._proportionalValveFlowmeter0Adc;
            _proportionalValveFlowmeter0TargetFlowrate = other._proportionalValveFlowmeter0TargetFlowrate;
            _proportionalValveFlowmeter1Adc = other._proportionalValveFlowmeter1Adc;
            _proportionalValveFlowmeter1TargetFlowrate = other._proportionalValveFlowmeter1TargetFlowrate;
            _proportionalValveFlowmeter2Adc = other._proportionalValveFlowmeter2Adc;
            _proportionalValveFlowmeter2TargetFlowrate = other._proportionalValveFlowmeter2TargetFlowrate;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="leak_flowmeter_adc")]
        public int LeakFlowmeterAdc
        {
            get
            {
                return _leakFlowmeterAdc;
            }
            set
            {
                _leakFlowmeterAdc = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="leak_threshold")]
        public double LeakThreshold
        {
            get
            {
                return _leakThreshold;
            }
            set
            {
                _leakThreshold = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="manual_flometer_adc")]
        public int ManualFlometerAdc
        {
            get
            {
                return _manualFlometerAdc;
            }
            set
            {
                _manualFlometerAdc = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="manual_flowmeter_target_flow_rate")]
        public double ManualFlowmeterTargetFlowRate
        {
            get
            {
                return _manualFlowmeterTargetFlowRate;
            }
            set
            {
                _manualFlowmeterTargetFlowRate = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="manual_flowmeter_flow_rate_tolerance")]
        public double ManualFlowmeterFlowRateTolerance
        {
            get
            {
                return _manualFlowmeterFlowRateTolerance;
            }
            set
            {
                _manualFlowmeterFlowRateTolerance = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="proportional_valve_flowmeter_0_adc")]
        public int ProportionalValveFlowmeter0Adc
        {
            get
            {
                return _proportionalValveFlowmeter0Adc;
            }
            set
            {
                _proportionalValveFlowmeter0Adc = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="proportional_valve_flowmeter_0_target_flowrate")]
        public double ProportionalValveFlowmeter0TargetFlowrate
        {
            get
            {
                return _proportionalValveFlowmeter0TargetFlowrate;
            }
            set
            {
                _proportionalValveFlowmeter0TargetFlowrate = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="proportional_valve_flowmeter_1_adc")]
        public int ProportionalValveFlowmeter1Adc
        {
            get
            {
                return _proportionalValveFlowmeter1Adc;
            }
            set
            {
                _proportionalValveFlowmeter1Adc = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="proportional_valve_flowmeter_1_target_flowrate")]
        public double ProportionalValveFlowmeter1TargetFlowrate
        {
            get
            {
                return _proportionalValveFlowmeter1TargetFlowrate;
            }
            set
            {
                _proportionalValveFlowmeter1TargetFlowrate = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="proportional_valve_flowmeter_2_adc")]
        public int ProportionalValveFlowmeter2Adc
        {
            get
            {
                return _proportionalValveFlowmeter2Adc;
            }
            set
            {
                _proportionalValveFlowmeter2Adc = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="proportional_valve_flowmeter_2_target_flowrate")]
        public double ProportionalValveFlowmeter2TargetFlowrate
        {
            get
            {
                return _proportionalValveFlowmeter2TargetFlowrate;
            }
            set
            {
                _proportionalValveFlowmeter2TargetFlowrate = value;
            }
        }
    
        public System.IObservable<FluidicSettings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new FluidicSettings(this)));
        }
    
        public System.IObservable<FluidicSettings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new FluidicSettings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("LeakFlowmeterAdc = " + _leakFlowmeterAdc + ", ");
            stringBuilder.Append("LeakThreshold = " + _leakThreshold + ", ");
            stringBuilder.Append("ManualFlometerAdc = " + _manualFlometerAdc + ", ");
            stringBuilder.Append("ManualFlowmeterTargetFlowRate = " + _manualFlowmeterTargetFlowRate + ", ");
            stringBuilder.Append("ManualFlowmeterFlowRateTolerance = " + _manualFlowmeterFlowRateTolerance + ", ");
            stringBuilder.Append("ProportionalValveFlowmeter0Adc = " + _proportionalValveFlowmeter0Adc + ", ");
            stringBuilder.Append("ProportionalValveFlowmeter0TargetFlowrate = " + _proportionalValveFlowmeter0TargetFlowrate + ", ");
            stringBuilder.Append("ProportionalValveFlowmeter1Adc = " + _proportionalValveFlowmeter1Adc + ", ");
            stringBuilder.Append("ProportionalValveFlowmeter1TargetFlowrate = " + _proportionalValveFlowmeter1TargetFlowrate + ", ");
            stringBuilder.Append("ProportionalValveFlowmeter2Adc = " + _proportionalValveFlowmeter2Adc + ", ");
            stringBuilder.Append("ProportionalValveFlowmeter2TargetFlowrate = " + _proportionalValveFlowmeter2TargetFlowrate);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class WhiteRabbit
    {
    
        private string _comPort;
    
        public WhiteRabbit()
        {
        }
    
        protected WhiteRabbit(WhiteRabbit other)
        {
            _comPort = other._comPort;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="com_port")]
        public string ComPort
        {
            get
            {
                return _comPort;
            }
            set
            {
                _comPort = value;
            }
        }
    
        public System.IObservable<WhiteRabbit> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new WhiteRabbit(this)));
        }
    
        public System.IObservable<WhiteRabbit> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new WhiteRabbit(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("ComPort = " + _comPort + ", ");
            stringBuilder.Append("PokePin = " + _pokePin + ", ");
            stringBuilder.Append("MaxOdorDeliveryTimeUs = " + _maxOdorDeliveryTimeUs + ", ");
            stringBuilder.Append("MinPokeTimeUs = " + _minPokeTimeUs + ", ");
            stringBuilder.Append("MinOdorDeliveryTimeUs = " + _minOdorDeliveryTimeUs + ", ");
            stringBuilder.Append("OdorTransitionTimeUs = " + _odorTransitionTimeUs + ", ");
            stringBuilder.Append("PokePin = " + _pokePin + ", ");
            stringBuilder.Append("VacuumSetupTimeUs = " + _vacuumSetupTimeUs + ", ");
            stringBuilder.Append("VacuumCloseTimeUs = " + _vacuumCloseTimeUs + ", ");
            stringBuilder.Append("OdorDwellTimeUs = " + _odorDwellTimeUs + ", ");
            stringBuilder.Append("ComPort = " + _comPort);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HardwareSchema
    {
    
        private string _subjectId;
    
        private string _sessionTime;
    
        private string _loggingRootPath;
    
        private string _remoteTransferRootPath;
    
        private string _robocopyScriptPath;
    
        private DelphiController _delphiController;
    
        private CameraSettings _cameraSettings;
    
        private CameraSettings1 _cameraSettings1;
    
        private FluidicSettings _fluidicSettings;
    
        private DeLuxDriver _deluxDriver;
    
        private WhiteRabbit _whiteRabbit;
    
        public HardwareSchema()
        {
            _delphiController = new DelphiController();
            _cameraSettings = new CameraSettings();
            _cameraSettings1 = new CameraSettings1();
            _fluidicSettings = new FluidicSettings();
            _deluxDriver = new DeLuxDriver();
            _whiteRabbit = new WhiteRabbit();
        }
    
        protected HardwareSchema(HardwareSchema other)
        {
            _subjectId = other._subjectId;
            _sessionTime = other._sessionTime;
            _loggingRootPath = other._loggingRootPath;
            _remoteTransferRootPath = other._remoteTransferRootPath;
            _robocopyScriptPath = other._robocopyScriptPath;
            _delphiController = other._delphiController;
            _cameraSettings = other._cameraSettings;
            _cameraSettings1 = other._cameraSettings1;
            _fluidicSettings = other._fluidicSettings;
            _deluxDriver = other._deluxDriver;
            _whiteRabbit = other._whiteRabbit;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="subject_id")]
        public string SubjectId
        {
            get
            {
                return _subjectId;
            }
            set
            {
                _subjectId = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="session_time")]
        public string SessionTime
        {
            get
            {
                return _sessionTime;
            }
            set
            {
                _sessionTime = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="logging_root_path")]
        public string LoggingRootPath
        {
            get
            {
                return _loggingRootPath;
            }
            set
            {
                _loggingRootPath = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="remote_transfer_root_path")]
        public string RemoteTransferRootPath
        {
            get
            {
                return _remoteTransferRootPath;
            }
            set
            {
                _remoteTransferRootPath = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="robocopy_script_path")]
        public string RobocopyScriptPath
        {
            get
            {
                return _robocopyScriptPath;
            }
            set
            {
                _robocopyScriptPath = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="delphi_controller")]
        public DelphiController DelphiController
        {
            get
            {
                return _delphiController;
            }
            set
            {
                _delphiController = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera_settings")]
        public CameraSettings CameraSettings
        {
            get
            {
                return _cameraSettings;
            }
            set
            {
                _cameraSettings = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera_settings1")]
        public CameraSettings1 CameraSettings1
        {
            get
            {
                return _cameraSettings1;
            }
            set
            {
                _cameraSettings1 = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="fluidic_settings")]
        public FluidicSettings FluidicSettings
        {
            get
            {
                return _fluidicSettings;
            }
            set
            {
                _fluidicSettings = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="delux_driver")]
        public DeLuxDriver DeluxDriver
        {
            get
            {
                return _deluxDriver;
            }
            set
            {
                _deluxDriver = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="white_rabbit")]
        public WhiteRabbit WhiteRabbit
        {
            get
            {
                return _whiteRabbit;
            }
            set
            {
                _whiteRabbit = value;
            }
        }
    
        public System.IObservable<HardwareSchema> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HardwareSchema(this)));
        }
    
        public System.IObservable<HardwareSchema> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HardwareSchema(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("SubjectId = " + _subjectId + ", ");
            stringBuilder.Append("SessionTime = " + _sessionTime + ", ");
            stringBuilder.Append("LoggingRootPath = " + _loggingRootPath + ", ");
            stringBuilder.Append("RemoteTransferRootPath = " + _remoteTransferRootPath + ", ");
            stringBuilder.Append("RobocopyScriptPath = " + _robocopyScriptPath + ", ");
            stringBuilder.Append("DelphiController = " + _delphiController + ", ");
            stringBuilder.Append("CameraSettings = " + _cameraSettings + ", ");
            stringBuilder.Append("CameraSettings1 = " + _cameraSettings1 + ", ");
            stringBuilder.Append("FluidicSettings = " + _fluidicSettings + ", ");
            stringBuilder.Append("DeluxDriver = " + _deluxDriver + ", ");
            stringBuilder.Append("WhiteRabbit = " + _whiteRabbit);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<CameraSettings> source)
        {
            return Process<CameraSettings>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CameraSettings1> source)
        {
            return Process<CameraSettings1>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DeLuxDriver> source)
        {
            return Process<DeLuxDriver>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DelphiController> source)
        {
            return Process<DelphiController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<FluidicSettings> source)
        {
            return Process<FluidicSettings>(source);
        }

        public System.IObservable<string> Process(System.IObservable<WhiteRabbit> source)
        {
            return Process<WhiteRabbit>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HardwareSchema> source)
        {
            return Process<HardwareSchema>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraSettings>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraSettings1>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DeLuxDriver>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DelphiController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<FluidicSettings>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<WhiteRabbit>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HardwareSchema>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<HardwareSchema>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}