//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace HardwareSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CameraSettings
    {
    
        private int _frameRate;
    
        private double _dutyCycle;
    
        private string _serialNumber;
    
        public CameraSettings()
        {
        }
    
        protected CameraSettings(CameraSettings other)
        {
            _frameRate = other._frameRate;
            _dutyCycle = other._dutyCycle;
            _serialNumber = other._serialNumber;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="frame_rate")]
        public int FrameRate
        {
            get
            {
                return _frameRate;
            }
            set
            {
                _frameRate = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="duty_cycle")]
        public double DutyCycle
        {
            get
            {
                return _dutyCycle;
            }
            set
            {
                _dutyCycle = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="serial_number")]
        public string SerialNumber
        {
            get
            {
                return _serialNumber;
            }
            set
            {
                _serialNumber = value;
            }
        }
    
        public System.IObservable<CameraSettings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CameraSettings(this)));
        }
    
        public System.IObservable<CameraSettings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CameraSettings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("FrameRate = " + _frameRate + ", ");
            stringBuilder.Append("DutyCycle = " + _dutyCycle + ", ");
            stringBuilder.Append("SerialNumber = " + _serialNumber);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class DelphiController
    {
    
        private int _finalValveEnergizedTimeUs;
    
        private int _maxOdorDeliveryTimeUs;
    
        private int _minPokeTimeUs;
    
        private int _minOdorDeliveryTimeUs;
    
        private int _odorTransitionTimeUs;
    
        private int _pokePin;
    
        private int _vacuumSetupTimeUs;
    
        private string _comPort;
    
        public DelphiController()
        {
            _pokePin = 22;
        }
    
        protected DelphiController(DelphiController other)
        {
            _finalValveEnergizedTimeUs = other._finalValveEnergizedTimeUs;
            _maxOdorDeliveryTimeUs = other._maxOdorDeliveryTimeUs;
            _minPokeTimeUs = other._minPokeTimeUs;
            _minOdorDeliveryTimeUs = other._minOdorDeliveryTimeUs;
            _odorTransitionTimeUs = other._odorTransitionTimeUs;
            _pokePin = other._pokePin;
            _vacuumSetupTimeUs = other._vacuumSetupTimeUs;
            _comPort = other._comPort;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="final_valve_energized_time_us")]
        public int FinalValveEnergizedTimeUs
        {
            get
            {
                return _finalValveEnergizedTimeUs;
            }
            set
            {
                _finalValveEnergizedTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="max_odor_delivery_time_us")]
        public int MaxOdorDeliveryTimeUs
        {
            get
            {
                return _maxOdorDeliveryTimeUs;
            }
            set
            {
                _maxOdorDeliveryTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_poke_time_us")]
        public int MinPokeTimeUs
        {
            get
            {
                return _minPokeTimeUs;
            }
            set
            {
                _minPokeTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="min_odor_delivery_time_us")]
        public int MinOdorDeliveryTimeUs
        {
            get
            {
                return _minOdorDeliveryTimeUs;
            }
            set
            {
                _minOdorDeliveryTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_transition_time_us")]
        public int OdorTransitionTimeUs
        {
            get
            {
                return _odorTransitionTimeUs;
            }
            set
            {
                _odorTransitionTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="poke_pin")]
        public int PokePin
        {
            get
            {
                return _pokePin;
            }
            set
            {
                _pokePin = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="vacuum_setup_time_us")]
        public int VacuumSetupTimeUs
        {
            get
            {
                return _vacuumSetupTimeUs;
            }
            set
            {
                _vacuumSetupTimeUs = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="com_port")]
        public string ComPort
        {
            get
            {
                return _comPort;
            }
            set
            {
                _comPort = value;
            }
        }
    
        public System.IObservable<DelphiController> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DelphiController(this)));
        }
    
        public System.IObservable<DelphiController> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DelphiController(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("FinalValveEnergizedTimeUs = " + _finalValveEnergizedTimeUs + ", ");
            stringBuilder.Append("MaxOdorDeliveryTimeUs = " + _maxOdorDeliveryTimeUs + ", ");
            stringBuilder.Append("MinPokeTimeUs = " + _minPokeTimeUs + ", ");
            stringBuilder.Append("MinOdorDeliveryTimeUs = " + _minOdorDeliveryTimeUs + ", ");
            stringBuilder.Append("OdorTransitionTimeUs = " + _odorTransitionTimeUs + ", ");
            stringBuilder.Append("PokePin = " + _pokePin + ", ");
            stringBuilder.Append("VacuumSetupTimeUs = " + _vacuumSetupTimeUs + ", ");
            stringBuilder.Append("ComPort = " + _comPort);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class LineMapping
    {
    
        private string _odorName;
    
        private int _odorIndex;
    
        public LineMapping()
        {
        }
    
        protected LineMapping(LineMapping other)
        {
            _odorName = other._odorName;
            _odorIndex = other._odorIndex;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_name")]
        public string OdorName
        {
            get
            {
                return _odorName;
            }
            set
            {
                _odorName = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_index")]
        public int OdorIndex
        {
            get
            {
                return _odorIndex;
            }
            set
            {
                _odorIndex = value;
            }
        }
    
        public System.IObservable<LineMapping> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LineMapping(this)));
        }
    
        public System.IObservable<LineMapping> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LineMapping(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OdorName = " + _odorName + ", ");
            stringBuilder.Append("OdorIndex = " + _odorIndex);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class LineMappings
    {
    
        private System.Collections.Generic.List<LineMapping> _odorMappings;
    
        private int _portLine;
    
        private int _vacuumLine;
    
        public LineMappings()
        {
            _odorMappings = new System.Collections.Generic.List<LineMapping>();
        }
    
        protected LineMappings(LineMappings other)
        {
            _odorMappings = other._odorMappings;
            _portLine = other._portLine;
            _vacuumLine = other._vacuumLine;
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="odor_mappings")]
        public System.Collections.Generic.List<LineMapping> OdorMappings
        {
            get
            {
                return _odorMappings;
            }
            set
            {
                _odorMappings = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="port_line")]
        public int PortLine
        {
            get
            {
                return _portLine;
            }
            set
            {
                _portLine = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="vacuum_line")]
        public int VacuumLine
        {
            get
            {
                return _vacuumLine;
            }
            set
            {
                _vacuumLine = value;
            }
        }
    
        public System.IObservable<LineMappings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LineMappings(this)));
        }
    
        public System.IObservable<LineMappings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LineMappings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("OdorMappings = " + _odorMappings + ", ");
            stringBuilder.Append("PortLine = " + _portLine + ", ");
            stringBuilder.Append("VacuumLine = " + _vacuumLine);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HardwareSchema
    {
    
        private string _animalId;
    
        private string _loggingRootPath;
    
        private string _remoteTransferRootPath;
    
        private DelphiController _delphiController;
    
        private CameraSettings _cameraSettings;
    
        private LineMappings _mappings;
    
        public HardwareSchema()
        {
            _delphiController = new DelphiController();
            _cameraSettings = new CameraSettings();
            _mappings = new LineMappings();
        }
    
        protected HardwareSchema(HardwareSchema other)
        {
            _animalId = other._animalId;
            _loggingRootPath = other._loggingRootPath;
            _remoteTransferRootPath = other._remoteTransferRootPath;
            _delphiController = other._delphiController;
            _cameraSettings = other._cameraSettings;
            _mappings = other._mappings;
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="animal_id")]
        public string AnimalId
        {
            get
            {
                return _animalId;
            }
            set
            {
                _animalId = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="logging_root_path")]
        public string LoggingRootPath
        {
            get
            {
                return _loggingRootPath;
            }
            set
            {
                _loggingRootPath = value;
            }
        }
    
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="remote_transfer_root_path")]
        public string RemoteTransferRootPath
        {
            get
            {
                return _remoteTransferRootPath;
            }
            set
            {
                _remoteTransferRootPath = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="delphi_controller")]
        public DelphiController DelphiController
        {
            get
            {
                return _delphiController;
            }
            set
            {
                _delphiController = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="camera_settings")]
        public CameraSettings CameraSettings
        {
            get
            {
                return _cameraSettings;
            }
            set
            {
                _cameraSettings = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="mappings")]
        public LineMappings Mappings
        {
            get
            {
                return _mappings;
            }
            set
            {
                _mappings = value;
            }
        }
    
        public System.IObservable<HardwareSchema> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HardwareSchema(this)));
        }
    
        public System.IObservable<HardwareSchema> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HardwareSchema(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("AnimalId = " + _animalId + ", ");
            stringBuilder.Append("LoggingRootPath = " + _loggingRootPath + ", ");
            stringBuilder.Append("RemoteTransferRootPath = " + _remoteTransferRootPath + ", ");
            stringBuilder.Append("DelphiController = " + _delphiController + ", ");
            stringBuilder.Append("CameraSettings = " + _cameraSettings + ", ");
            stringBuilder.Append("Mappings = " + _mappings);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<CameraSettings> source)
        {
            return Process<CameraSettings>(source);
        }

        public System.IObservable<string> Process(System.IObservable<DelphiController> source)
        {
            return Process<DelphiController>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LineMapping> source)
        {
            return Process<LineMapping>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LineMappings> source)
        {
            return Process<LineMappings>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HardwareSchema> source)
        {
            return Process<HardwareSchema>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.6.1.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CameraSettings>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DelphiController>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LineMapping>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LineMappings>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HardwareSchema>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<HardwareSchema>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                    .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}